services:
  nestapp:
    build: Ecommerce_Backend:latest
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
